### ISSUE TITLE
Update to @nestjs/common@7.6.13

### ISSUE THREAD

**Issue by paulbijancoch** [SkyPressATX/nestjs-dynamodb#1]
Hey @skypress-bmo 
will this package be updated to a current nestjs-version? I'd love to help you on that.

**Comment by ghost** [comment]
Hi Paul, that would be great if you have the time. I used this for one small project that wrapped a few weeks after it started. Feel free to create a PR or Fork this repo for your own use.

^_^

**Comment by paulbijancoch** [comment]
Hey @skypress-bmo I did a Pull Request right here https://github.com/SkyPressATX/nestjs-dynamodb/pull/2 😊

**Comment by BMO-tech** [comment]
Thanks for the wait, I've been able to merge your changes and publish `0.1.0`. Let me know if that works out for you.

**Comment by paulbijancoch** [comment]
Jackpooot life 🎉🌴 thank you. I am already looking forward to get this
into production 😊

Best,

Paul

Ben Moore ***@***.***> schrieb am Fr. 19. März 2021 um 18:49:
